version: '3.9'

services:
  db:
    image: postgres:16
    container_name: echo_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: echo_user
      POSTGRES_PASSWORD: echo_password
      POSTGRES_DB: echo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
